### ISSUE TITLE
Human Grunts Play Animations Slower Than They Should

### ISSUE THREAD

**Issue by epicplayer40** [VJ-HLR-Developers/Half-Life-Resurgence#7] opened 2020-04-19 21:25 UTC
I'm not sure what causes this, but sometimes during combat the Human Grunts will play their animations at a very slow rate and remain this way until they die.

**Comment by DrVrej** [comment] 2020-04-19 22:59
It was caused by the new playback support in VJ Base, fixed in latest push

**Closed by DrVrej** 2020-04-19 22:59 UTC
Labels: bug
